### ISSUE TITLE
Login optimieren

### ISSUE THREAD

**Issue by yannik995** [yannik995/StudIP-Downloader#4]
Der Login kann optimiert werden, da der Umweg über das Session Cookie nervig ist.

**Comment by Sopor10** [comment]
Ich habe das Auslesen des "Seminar_Session" Cookies mit Selenium automatisiert.
Wenn ich dazu komme, kann ich noch einen PullRequest dazu erstellen.
Der relevante Code für den Login ist im LoginActivityServiceWithSelenium in meinem Fork.

**Comment by yannik995** [comment]
Hallo,
das sieht echt gut aus, davon kannst du gerne einen PullRequest stellen.
Finde es aber gut, wenn die Version weiterhin ohne Docker funktioniert, damit es von mehr Nutzern nutzbar ist.
Würde dann auf deine Docker Version verweisen :)

Tendiere gerade dazu für mich deine Docker Version auf dem NAS laufen zu lassen, da ich es aktuell noch immer per Hand starte :D

**Comment by Bjoern-Boehnert** [comment]
Inhalte lassen sich über die REST-API mit "Basic Authentication" auslesen, dazu kann der Benutzername und das Passwort verwendet werden.

Als Curl: 
`curl -X GET https://elearning.uni-oldenburg.de/api.php/discovery -H "Authorization: Basic base64(Username:Passwort)"`

Ich hab mir das mit https://reqbin.com/ generieren lassen und bereits für mein Projekt in Java getestet. Funktioniert
Danke für das coole Projekt :) 👍

**Comment by yannik995** [comment]
Ach, das ist ja einfach. Hätte ich auch drauf kommen können :D 

Passe ich gleich mal an.

**Comment by Bjoern-Boehnert** [comment]
Danke für den fix. :)

**Comment by yannik995** [comment]
Damit erledigt :)
